//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher69.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdHistory { get; set; }
        public Nullable<int> IdTeacher { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> DateEvent { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Students Students { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
