//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher69.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teacher69Entities : DbContext
    {
        public teacher69Entities()
            : base("name=teacher69Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FormTime> FormTime { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Journals> Journals { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<TeacherHasSubjects> TeacherHasSubjects { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<YearAdd> YearAdd { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
